### ISSUE TITLE
Where is the implementation of orthogonal reparameterisation

### ISSUE THREAD

**Issue by Alexios-hub** [roymiles/vkd#1]
Hello, many thanks for the wonderful job and releasing the code! I've searched for the  implementation of orthogonal reparameterisation which is mentioned in the paper in the engine.py file and train.py file but only found 
`student.projector = torch.nn.utils.parametrizations.orthogonal(nn.Linear(student.num_features, teacher.num_features, bias=False))` then used it in the training:`z_s_pool = student.module.projector(z_s_pool)`, would you publish the implementation of orthogonal reparameterisation, or it is somewhere else in the proj?

**Comment by roymiles** [comment]
Hi Alexios! Thank you very much for showing an interest in our work. We chose to share the code using `torch.nn.utils.parametrizations` as we thought it would be tidier/easier. We have also already replicated the paper results using this library. However, if you would like to use pytorch primitives, this will work too:

```
class MyOrthogonal(nn.Module):
    def __init__(self, ds, dt):
        super(MyOrthogonal, self).__init__()
        self.ds = ds
        self.dt = dt
        self.weight = Parameter(torch.empty((dt, dt)))
        torch.nn.init.kaiming_uniform_(self.weight, a=math.sqrt(5))

    def forward(self, x):
        A = torch.linalg.matrix_exp(self.weight)
        P = A[:, 0:self.ds]
        y = F.linear(x, P)
        return y

student.projector = MyOrthogonal(student.num_features, teacher.num_features)
```

**Comment by Alexios-hub** [comment]
Hi roymiles! Thank you for your meticulous and helpful reply!  I was just wondering if using the pytorch orthogonal projection will work. Thanks again for this job and the code!

**Comment by connorlee77** [comment]
In your original code formulation, how are you making W skew symmetric such that the matrix exponential is orthogonal?

**Comment by roymiles** [comment]
Hi @connorlee77! The code shared above was not our original implemention but you're right, I must have overlooked that bit here. Sorry about that! 
We can enforce skew symmetry using W' = (W-W^T)/2 before the matrix exponential.

**Comment by connorlee77** [comment]
Got it, thanks!

**Comment by g1239** [comment]
> Hi Alexios! Thank you very much for showing an interest in our work. We chose to share the code using `torch.nn.utils.parametrizations` as we thought it would be tidier/easier. We have also already replicated the paper results using this library. However, if you would like to use pytorch primitives, this will work too:
> 
> ```
> class MyOrthogonal(nn.Module):
>     def __init__(self, ds, dt):
>         super(MyOrthogonal, self).__init__()
>         self.ds = ds
>         self.dt = dt
>         self.weight = Parameter(torch.empty((dt, dt)))
>         torch.nn.init.kaiming_uniform_(self.weight, a=math.sqrt(5))
> 
>     def forward(self, x):
>         A = torch.linalg.matrix_exp(self.weight)
>         P = A[:, 0:self.ds]
>         y = F.linear(x, P)
>         return y
> 
> student.projector = MyOrthogonal(student.num_features, teacher.num_features)
> ```

Thank you for excellent job. And can I understand this process as projector being orthogonal at initialization, but having parameter updates during training does not limit its orthogonality?

**Comment by connorlee77** [comment]
It doesn’t look like orthogonality is enforced at initialization actually. You’ll need to use the skew symmetric enforcing method that Roy mentioned to force orthogonality post parameter updates.

**Comment by g1239** [comment]
After checking pytorch source code and reading your reply, I accurately understood this process. Thanks!
