### ISSUE TITLE
Term clarification: Standardization vs. Whitening 

### ISSUE THREAD

**Issue by connorlee77** [roymiles/vkd#2]
I was wondering what the exact differences were between the standardization and whitening procedure you used in the paper. From my perspective, I believe standardization refers to zero mean, unit std normalization, while whitening refers to decorrelation via PCA. Is my understanding correct? And do you guys do whitening in the code right now? I only see the layer norm in play.

**Comment by roymiles** [comment]
Yup, that is correct. Whitened features have an identity covariance i.e. decorrelation like you said. For standardisation, we do the normalisation along the depth, which is the same as a layer norm. The whitening was used for the generative tasks in the paper, which is not part of this repository.

I can check and share the exact whitening code if you would like when I am back at home, but if not something like: https://github.com/htdt/self-supervised/blob/master/methods/whitening.py
should work too. Hope this helps.
