### ISSUE TITLE
The question about image generation

### ISSUE THREAD

**Issue by Zeudfish** [roymiles/vkd#6]
Hello, your idea is very cool, and I am eager to try it. However, I am engaged in low-level tasks, so I would like to ask if you can provide the code on image generation. It seems that I only found classification and object detection in the code base. At the same time, could you tell me the whitening and orthogonal projection code in the paper to realize the function

**Comment by roymiles** [comment]
Hi, I provided more details about the whitening and image generation here: https://github.com/roymiles/vkd/issues/3 and https://github.com/roymiles/vkd/issues/4. Are these of any help? In general the code is just a modified version fo KD-DLGAN with the additional orthogonal feature loss in place.
