### ISSUE TITLE
ViDT training code

### ISSUE THREAD

**Issue by zhd61** [roymiles/vkd#9]
Hi, 

thanks for the nice work. Will you please provide the 'vidt' folder with the implementation of the Orthogonal Projections? It has a link to it but is currently not available. I am interested in training the vkd model for detection. 

Cheers

**Comment by roymiles** [comment]
Hi,

Sorry about that, I have pushed the ViDT training code now. I am also currently finishing up re-running some of the teacher-student pairs to verify the results (as I was tidying it all up a bit).
